
TARGET =	lang4cpp
CC = g++

PPREFIX =  	hyve/lang/

SOURCES	=	Array.cpp \
			Binary.cpp \
			Bitmask.cpp \
			Boolean.cpp \
			Callback.cpp \
			Character.cpp \
			Class.cpp \
			Collection.cpp \
			Delegate.cpp \
			Event.cpp \
			Dispatcher.cpp \
			Enum.cpp \
			Float.cpp \
			Function.cpp \
			Int.cpp \
			Interface.cpp \
			List.cpp \
			Map.cpp \
			Member.cpp \
			Method.cpp \
			ObservableEvent.cpp \
			Observer.cpp \
			Primitive.cpp \
			Procedure.cpp \
			Sequence.cpp \
			Struct.cpp \
			Text.cpp \
			Type.cpp \
			Typedef.cpp \
			Uint.cpp \
			hyve.cpp \
			Object.cpp \
			_type.cpp \
			_meta.cpp \
			ll.cpp \
			serializer.cpp

INCLUDE = 	$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/public/cpp/include \
			$(BUILDHOME)/infra/include \
			$(BUILDHOME)/interface/api/include

LIBS	=	lang fl api

include $(BUILD)/componentcpp.makefile
