
TARGET =	../test/bin/tc_jsonser

SOURCES =	tc_jsonser__api.c \
			tc_jsonser__meta.c \
			tc_jsonser.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/interface/json/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang json
LIBPATH	=	

include $(BUILD)/executable.makefile

