
TARGET =	../test/bin/tc_jsonser_number

SOURCES =	tc_jsonser_number__api.c \
			tc_jsonser_number__meta.c \
			tc_jsonser_number.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/interface/json/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang json
LIBPATH	=	

include $(BUILD)/executable.makefile

