
TARGET =	../test/bin/tc_jsonser_number

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/interface/json/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang json
LIBPATH	=	

include $(BUILD)/executable.makefile

