
TARGET =	../test/bin/tc_stringser

SOURCES =	tc_stringser__api.c \
			tc_stringser__meta.c \
			tc_stringser.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/infra/include

LIBS	= lang infra 
LIBPATH	=	

include $(BUILD)/executable.makefile

