
TARGET =	os

SOURCES	=	os.c \
			os__meta.c \
			os_thread.c \
			os_timer.c \
			os_time.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/infra/include

LIBS	=	lang fl

include $(BUILD)/component.makefile

