
TARGET =	os

SOURCES	=	os.c \
			os__meta.c \
			os_Thread.c \
			os_Timer.c \
			os_Time.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/infra/include \
			$(BUILDHOME)/interface/api/include

LIBS	=	lang fl api

include $(BUILD)/component.makefile

