/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include prebake.h
 * in your main project file. Do not edit! */

#ifndef CORTO/C_PREBAKED_H
#define CORTO/C_PREBAKED_H

/* Headers of public dependencies */
#include <corto>

/* Headers of private dependencies */
#ifdef CORTO/C_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if CORTO/C_IMPL && defined _MSC_VER
#define CORTO/C_EXPORT __declspec(dllexport)
#elif CORTO/C_IMPL
#define CORTO/C_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define CORTO/C_EXPORT __declspec(dllimport)
#else
#define CORTO/C_EXPORT
#endif

#endif

