
TARGET =	hyvedev

SOURCES =	db_arg.c \
			db_file.c \
			db_generator.c \
			db_generatorDepWalk.c \
			db_generatorTypeDepWalk.c \
			db_ic_assemble.c \
			db_ic.c
			

INCLUDE = 	include $(BUILDHOME)/db/include $(BUILDHOME)/db/src $(BUILDHOME)/public/c/include

LIBS	= lang dl
LIBPATH	=	

include $(BUILD)/component.makefile

