
TARGET =	cpp_common

SOURCES =	cpp_common.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/dev/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang hyvedev
LIBPATH	=	

include $(BUILD)/component.makefile

