
TARGET =	xml

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/dev/include \
			$(BUILDHOME)/public/c/include \
			/usr/include/libxml2

LIBS	= lang xml2
LIBPATH	=	

include $(BUILD)/component.makefile

