
TARGET  = html

INCLUDE = include \
          $(CORTEX_HOME)/cx/include \
          $(CORTEX_HOME)/dev/include \
          $(CORTEX_HOME)/public/c/include \
          $(CORTEX_HOME)/interface/json/include

LIBS    = lang cortexdev json
LIBPATH =

include $(CORTEX_HOME)/build/generator.makefile

