
TARGET  = html

INCLUDE = include \
          $(HYVE_HOME)/db/include \
          $(HYVE_HOME)/dev/include \
          $(HYVE_HOME)/public/c/include \
          $(HYVE_HOME)/interface/json/include

LIBS    = lang hyvedev json
LIBPATH =

include $(HYVE_HOME)/build/generator.makefile

