/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef CREATE_SELF_PACKAGE_BAKE_CONFIG_H
#define CREATE_SELF_PACKAGE_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <corto>
#include <corto.c>
#include <bake.util>

/* Headers of private dependencies */
#ifdef CREATE_SELF_PACKAGE_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if CREATE_SELF_PACKAGE_IMPL && defined _MSC_VER
#define CREATE_SELF_PACKAGE_EXPORT __declspec(dllexport)
#elif CREATE_SELF_PACKAGE_IMPL
#define CREATE_SELF_PACKAGE_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define CREATE_SELF_PACKAGE_EXPORT __declspec(dllimport)
#else
#define CREATE_SELF_PACKAGE_EXPORT
#endif

#endif

