
TARGET =	fast

LEX		=	fast.l
YACC	= 	fast.y

INCLUDE = 	$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			include \
			$(BUILDHOME)/dev/include

LIBS	=	lang hyvedev fl

include $(BUILD)/lexyacc.makefile

