
all:
	@make -C common
	@make -C type
	@make -C class
	@make -C load

clean:
	@make clean -C common
	@make clean -C type
	@make clean -C class
	@make clean -C load
	
gcov:
	@make gcov -C common
	@make gcov -C type
	@make gcov -C class
	@make gcov -C load
	
splint:
	@make splint -C common
	@make splint -C type
	@make splint -C class
	@make splint -C load
	

