
TARGET =	io

SOURCES	=	io.c \
			io__wrapper.c \
			io__meta.c \
			io_file.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/infra/include

LIBS	=	lang fl 

include $(BUILD)/component.makefile

