
TARGET =	io

SOURCES	=	io.c \
			io__meta.c \
			io_File.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/infra/include \
			$(BUILDHOME)/interface/api/include

LIBS	=	lang fl api

include $(BUILD)/component.makefile

