
TARGET =	../test/bin/tc_event

SOURCES =	tc_event__api.c \
			tc_event__meta.c \
			tc_Point.c \
			tc.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang 
LIBPATH	=	

include $(BUILD)/executable.makefile

