
TARGET  = html

INCLUDE = include \
          $(CORTO_HOME)/cx/include \
          $(CORTO_HOME)/dev/include \
          $(CORTO_HOME)/public/c/include \
          $(CORTO_HOME)/interface/json/include

LIBS    = corto cortodev json
LIBPATH =

include $(CORTO_HOME)/build/generator.makefile

