
TARGET =	../test/bin/tc_call

SOURCES =	tc_Animal.c \
			tc_Mammal.c \
			tc_call__meta.c \
			tc_call__api.c \
			tc_call.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang 
LIBPATH	=	

include $(BUILD)/executable.makefile

