
TARGET =	lang

SOURCES =	db.c \
			db_async.c \
			db_call.c \
			db_class.c \
			db_collection.c \
            db_compare_ser.c \
			db_convert.c \
            db_copy_ser.c \
			db_dispatcher.c \
			db_dl.c \
			db_err.c \
			db_expr.c \
            db_init_ser.c \
			db_interface.c \
			db_ll.c \
			db_loader.c \
			db_metawalk.c \
			db_member.c \
			db_memory_ser.c \
			db_object.c \
			db_operator.c \
			db_primitive.c \
			db_procedure.c \
			db_rbtree.c \
			jsw_rbtree.c \
			db_serializer.c \
			db_string.c \
			db_string_deser.c \
			db_string_ser.c \
			db_struct.c \
			db_time.c \
			db_typedef.c \
			db_type.c \
			db_value.c \
			db_vm.c

INCLUDE = 	include

LIBS	= rt dl m
LIBPATH	=	

include $(BUILD)/component.makefile