
TARGET =	lang

SOURCES =	db.c \
			db__api.c \
			db__wrapper.c \
			db_alias.c \
			db_array.c \
			db_async.c \
			db_binary.c \
			db_bitmask.c \
			db_boolean.c \
			db_call.c \
			db_callback.c \
			db_character.c \
			db_class.c \
			db_collection.c \
            db_compare_ser.c \
            db_constant.c \
			db_convert.c \
            db_copy_ser.c \
            db_delegate.c \
			db_dispatcher.c \
			db_dl.c \
			db_enum.c \
			db_err.c \
			db_event.c \
			db_expr.c \
			db_float.c \
			db_function.c \
            db_init_ser.c \
            db_int.c \
			db_interface.c \
			db_list.c \
			db_ll.c \
			db_loader.c \
			db_map.c \
			db_member.c \
			db_memory_ser.c \
			db_metaprocedure.c \
			db_metawalk.c \
			db_method.c \
			db_object.c \
			db_observer.c \
			db_operator.c \
			db_primitive.c \
			db_procedure.c \
			db_rbtree.c \
			db_sequence.c \
			db_serializer.c \
			db_string.c \
			db_string_deser.c \
			db_string_ser.c \
			db_struct.c \
			db_text.c \
			db_time.c \
			db_type.c \
			db_typedef.c \
			db_uint.c \
			db_value.c \
			db_virtual.c \
			db_vm.c \
			jsw_rbtree.c 

INCLUDE = 	include ../public/c/include

LIBS	= rt dl m
LIBPATH	=	

include $(BUILD)/component.makefile