
all:
	@make -C xml
	@make -C json
	@make -C fast
	
clean:
	@make clean -C xml
	@make clean -C json
	@make clean -C fast
	
gcov:
	@make gcov -C xml
	@make gcov -C json
	@make gcov -C fast
	
splint:
	@make splint -C xml
	@make splint -C json
	@make splint -C fast
	

