
all:
	@make -C common
	@make -C type
	@make -C load
	@make -C interface
	@make -C api
	
clean:
	@make clean -C common
	@make clean -C type
	@make clean -C load
	@make clean -C interface
	@make clean -C api
	
gcov:
	@make gcov -C common
	@make gcov -C type
	@make gcov -C load
	@make gcov -C interface
	@make gcov -C api
	
splint:
	@make splint -C common
	@make splint -C type
	@make splint -C load
	@make splint -C interface
	@make splint -C api
	

