
TARGET =	math

SOURCES	=	mth.c \
			math__meta.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/infra/include

LIBS	=	lang fl api m

include $(BUILD)/component.makefile

