
TARGET =	hyve

SOURCES =	hyve.c

INCLUDE = 	include -I $(BUILDHOME)/db/include -I $(BUILDHOME)/public/c/include -I $(BUILDHOME)/infra/include

LIBS	= lang
LIBPATH	=	

include $(BUILD)/executable.makefile

