
TARGET =	c_common

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/dev/include \
			$(BUILDHOME)/public/c/include

LIBS	= lang hyvedev
LIBPATH	=	

include $(BUILD)/generator.makefile

