
TARGET =	cpp_class

SOURCES =	cpp_class.c \
			cpp_impl.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/dev/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/generator/cpp/common/include

OBJECTS = ../common/obj/cpp_common.o
LIBS	= lang hyvedev
LIBPATH	=	

include $(BUILD)/generator.makefile

