
TARGET =	c_interface

SOURCES =	c_interface.c

INCLUDE = 	include \
			$(BUILDHOME)/db/include \
			$(BUILDHOME)/dev/include \
			$(BUILDHOME)/public/c/include \
			$(BUILDHOME)/generator/c/common/include

LIBS	= lang hyvedev :c_common
LIBPATH	=	

include $(BUILD)/generator.makefile

